DROP TABLE IF EXISTS products;
CREATE TABLE products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    image TEXT,
    category TEXT NOT NULL,
    price REAL NOT NULL,
    stock INTEGER NOT NULL,
    rating REAL DEFAULT 4.5,
    discount INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT 0,
    sales_count INTEGER DEFAULT 0,
    ai_score REAL DEFAULT 0.5,
    created DATE DEFAULT CURRENT_DATE
);

INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Tailored Suit 1', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium1.jpg', 'men_PREMIUM', 140.61, 21, 3.8, 0, 0, 387, 0.42);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Silk Blazer 2', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium2.jpg', 'men_PREMIUM', 188.94, 8, 4.6, 20, 0, 288, 0.38);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Classic Tuxedo 3', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium3.jpg', 'men_PREMIUM', 110.08, 65, 4.6, 20, 0, 413, 0.09);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Luxury Watch 4', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium4.jpg', 'men_PREMIUM', 199.48, 90, 3.9, 0, 1, 131, 0.01);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Handmade Oxfords 5', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium5.jpg', 'men_PREMIUM', 144.66, 48, 4.1, 20, 0, 329, 0.36);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Leather Briefcase 6', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium6.jpg', 'men_PREMIUM', 120.88, 44, 4.2, 10, 0, 278, 0.83);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Silk Tie Set 7', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium7.jpg', 'men_PREMIUM', 136.49, 126, 3.7, 20, 0, 391, 0.59);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Cashmere Knitwear 8', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium8.jpg', 'men_PREMIUM', 105.43, 55, 4.0, 20, 1, 303, 0.85);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Premium Wool Coat 9', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium9.jpg', 'men_PREMIUM', 125.59, 89, 4.6, 20, 0, 269, 0.28);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Designer Dress Shirt 10', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium10.jpg', 'men_PREMIUM', 146.53, 40, 4.9, 5, 1, 192, 0.54);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Tailored Suit 11', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium11.jpg', 'men_PREMIUM', 188.81, 20, 4.7, 15, 0, 486, 0.41);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Silk Blazer 12', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium12.jpg', 'men_PREMIUM', 158.30, 70, 4.1, 5, 1, 292, 0.73);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Classic Tuxedo 13', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium13.jpg', 'men_PREMIUM', 178.31, 120, 4.4, 0, 1, 323, 0.25);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Luxury Watch 14', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium14.jpg', 'men_PREMIUM', 192.31, 70, 3.6, 5, 0, 258, 0.76);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Handmade Oxfords 15', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium15.jpg', 'men_PREMIUM', 153.02, 66, 4.5, 5, 0, 377, 0.49);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Leather Briefcase 16', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium16.jpg', 'men_PREMIUM', 177.20, 126, 4.8, 20, 0, 128, 0.49);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Silk Tie Set 17', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium17.jpg', 'men_PREMIUM', 189.48, 103, 3.6, 15, 1, 153, 0.66);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Cashmere Knitwear 18', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium18.jpg', 'men_PREMIUM', 180.03, 111, 4.7, 10, 0, 428, 0.95);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Premium Wool Coat 19', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium19.jpg', 'men_PREMIUM', 166.04, 81, 3.8, 15, 0, 78, 1.00);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Premium Designer Dress Shirt 20', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'men_premium20.jpg', 'men_PREMIUM', 149.40, 26, 4.4, 10, 0, 112, 0.55);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Evening Gala Gown 1', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium1.jpg', 'women_PREMIUM', 165.48, 54, 4.5, 5, 0, 107, 0.69);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Designer Cocktail Dress 2', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium2.jpg', 'women_PREMIUM', 172.86, 21, 4.5, 10, 0, 416, 0.79);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Luxury Leather Handbag 3', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium3.jpg', 'women_PREMIUM', 124.93, 10, 4.0, 20, 0, 258, 0.83);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Signature Stilettos 4', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium4.jpg', 'women_PREMIUM', 140.47, 90, 3.8, 15, 1, 291, 0.10);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Fine Pearl Necklace 5', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium5.jpg', 'women_PREMIUM', 118.20, 14, 3.9, 20, 0, 17, 0.02);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Italian Silk Blouse 6', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium6.jpg', 'women_PREMIUM', 185.62, 124, 4.9, 5, 0, 46, 0.21);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Cashmere Wrap Coat 7', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium7.jpg', 'women_PREMIUM', 105.67, 50, 4.4, 0, 0, 121, 0.11);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Diamond Stud Earrings 8', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium8.jpg', 'women_PREMIUM', 175.59, 63, 3.6, 15, 0, 389, 0.26);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Lace Overlay Dress 9', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium9.jpg', 'women_PREMIUM', 168.85, 32, 3.6, 20, 1, 241, 0.70);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Velvet Evening Blazer 10', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium10.jpg', 'women_PREMIUM', 159.69, 106, 4.7, 20, 0, 176, 0.84);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Evening Gala Gown 11', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium11.jpg', 'women_PREMIUM', 172.31, 144, 4.7, 15, 0, 246, 0.87);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Designer Cocktail Dress 12', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium12.jpg', 'women_PREMIUM', 162.21, 38, 4.9, 15, 0, 81, 0.28);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Luxury Leather Handbag 13', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium13.jpg', 'women_PREMIUM', 187.59, 40, 4.8, 10, 0, 485, 0.20);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Signature Stilettos 14', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium14.jpg', 'women_PREMIUM', 196.07, 106, 4.1, 15, 1, 58, 0.05);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Fine Pearl Necklace 15', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium15.jpg', 'women_PREMIUM', 119.35, 126, 4.6, 15, 0, 424, 0.96);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Italian Silk Blouse 16', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium16.jpg', 'women_PREMIUM', 122.21, 24, 4.2, 5, 0, 18, 0.71);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Cashmere Wrap Coat 17', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium17.jpg', 'women_PREMIUM', 114.42, 132, 4.3, 5, 0, 14, 0.57);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Diamond Stud Earrings 18', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium18.jpg', 'women_PREMIUM', 151.26, 78, 4.6, 5, 0, 70, 0.86);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Lace Overlay Dress 19', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium19.jpg', 'women_PREMIUM', 171.34, 25, 4.8, 10, 0, 48, 0.29);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Premium Velvet Evening Blazer 20', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'women_premium20.jpg', 'women_PREMIUM', 137.52, 98, 4.9, 15, 0, 178, 0.30);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Mini Formal Vest 1', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium1.jpg', 'kids_PREMIUM', 113.83, 50, 4.4, 5, 1, 292, 0.26);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Luxe Party Dress 2', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium2.jpg', 'kids_PREMIUM', 145.34, 147, 4.9, 5, 0, 33, 0.52);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Junior Smart Blazer 3', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium3.jpg', 'kids_PREMIUM', 152.78, 119, 3.6, 15, 0, 38, 0.99);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Patent Leather Loafers 4', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium4.jpg', 'kids_PREMIUM', 195.27, 55, 3.7, 15, 0, 292, 0.21);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Holiday Occasion Suit 5', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium5.jpg', 'kids_PREMIUM', 104.04, 101, 4.0, 20, 0, 271, 0.53);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Heirloom Embroidered Gown 6', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium6.jpg', 'kids_PREMIUM', 189.49, 112, 3.6, 5, 0, 88, 0.92);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Premium Quilted Jacket 7', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium7.jpg', 'kids_PREMIUM', 162.84, 113, 4.4, 20, 0, 174, 0.58);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Velvet Bowtie Set 8', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium8.jpg', 'kids_PREMIUM', 110.66, 94, 4.9, 10, 1, 225, 0.19);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Satin Ribbon Dress 9', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium9.jpg', 'kids_PREMIUM', 188.85, 49, 4.7, 0, 0, 199, 0.87);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Designer Baby Booties 10', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium10.jpg', 'kids_PREMIUM', 177.20, 112, 4.6, 15, 0, 388, 0.44);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Mini Formal Vest 11', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium11.jpg', 'kids_PREMIUM', 190.22, 134, 4.8, 10, 0, 160, 0.54);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Luxe Party Dress 12', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium12.jpg', 'kids_PREMIUM', 101.03, 90, 4.6, 10, 0, 169, 0.38);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Junior Smart Blazer 13', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium13.jpg', 'kids_PREMIUM', 197.80, 99, 4.3, 0, 0, 246, 0.14);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Patent Leather Loafers 14', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium14.jpg', 'kids_PREMIUM', 141.01, 74, 4.6, 5, 0, 314, 0.94);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Holiday Occasion Suit 15', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium15.jpg', 'kids_PREMIUM', 132.58, 68, 4.7, 20, 0, 99, 0.20);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Heirloom Embroidered Gown 16', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium16.jpg', 'kids_PREMIUM', 117.61, 56, 4.6, 15, 1, 324, 0.55);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Premium Quilted Jacket 17', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium17.jpg', 'kids_PREMIUM', 151.78, 28, 4.0, 0, 0, 178, 0.39);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Velvet Bowtie Set 18', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium18.jpg', 'kids_PREMIUM', 182.04, 18, 3.8, 10, 0, 285, 0.47);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Satin Ribbon Dress 19', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium19.jpg', 'kids_PREMIUM', 186.84, 5, 4.2, 5, 0, 110, 0.87);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Premium Designer Baby Booties 20', 'Exquisite craftsmanship meets timeless elegance for the discerning individual.', 'kids_premium20.jpg', 'kids_PREMIUM', 128.44, 65, 4.1, 15, 0, 267, 0.24);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Essential Cotton T-Shirt 1', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual1.jpg', 'men_CASUAL', 78.17, 48, 4.4, 10, 0, 246, 0.94);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Slim-Fit Indigo Jeans 2', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual2.jpg', 'men_CASUAL', 24.35, 38, 4.0, 0, 0, 56, 0.14);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Urban Everyday Sneakers 3', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual3.jpg', 'men_CASUAL', 56.89, 131, 4.7, 15, 0, 207, 0.40);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Over-sized Fleece Hoodie 4', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual4.jpg', 'men_CASUAL', 68.90, 82, 3.7, 0, 0, 302, 0.85);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Classic Piqué Polo 5', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual5.jpg', 'men_CASUAL', 82.59, 45, 4.6, 10, 0, 163, 0.58);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Rugged Cargo Pants 6', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual6.jpg', 'men_CASUAL', 49.37, 69, 4.3, 10, 0, 306, 0.22);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Vintage Denim Jacket 7', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual7.jpg', 'men_CASUAL', 73.12, 33, 4.0, 20, 0, 102, 0.10);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Premium Baseball Cap 8', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual8.jpg', 'men_CASUAL', 21.97, 68, 4.2, 5, 0, 173, 0.15);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Chino Walk Shorts 9', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual9.jpg', 'men_CASUAL', 44.50, 34, 4.6, 5, 0, 118, 0.03);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Brushed Flannel Shirt 10', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual10.jpg', 'men_CASUAL', 44.77, 56, 4.8, 5, 0, 18, 0.70);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Essential Cotton T-Shirt 11', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual11.jpg', 'men_CASUAL', 78.92, 106, 3.5, 15, 1, 490, 0.69);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Slim-Fit Indigo Jeans 12', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual12.jpg', 'men_CASUAL', 77.54, 111, 3.9, 10, 0, 320, 0.21);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Urban Everyday Sneakers 13', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual13.jpg', 'men_CASUAL', 39.51, 69, 4.0, 10, 0, 152, 0.96);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Over-sized Fleece Hoodie 14', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual14.jpg', 'men_CASUAL', 50.47, 43, 4.8, 10, 0, 247, 0.03);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Classic Piqué Polo 15', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual15.jpg', 'men_CASUAL', 31.03, 61, 4.4, 15, 0, 278, 0.36);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Rugged Cargo Pants 16', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual16.jpg', 'men_CASUAL', 41.40, 50, 4.5, 0, 0, 245, 0.63);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Vintage Denim Jacket 17', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual17.jpg', 'men_CASUAL', 39.77, 17, 4.1, 10, 0, 289, 0.91);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Premium Baseball Cap 18', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual18.jpg', 'men_CASUAL', 56.33, 16, 4.7, 20, 0, 268, 0.54);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Chino Walk Shorts 19', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual19.jpg', 'men_CASUAL', 98.46, 20, 3.9, 5, 0, 447, 0.63);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Men Casual Brushed Flannel Shirt 20', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'men_casual20.jpg', 'men_CASUAL', 88.66, 11, 5.0, 10, 0, 24, 0.91);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Floral Garden Sundress 1', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual1.jpg', 'women_CASUAL', 66.83, 150, 4.0, 15, 1, 299, 0.64);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual High-Rise Yoga Leggings 2', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual2.jpg', 'women_CASUAL', 92.67, 140, 4.7, 15, 0, 246, 0.12);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Soft Knit Cardigan 3', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual3.jpg', 'women_CASUAL', 96.09, 33, 4.9, 20, 0, 65, 0.80);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Comfort Leather Loafers 4', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual4.jpg', 'women_CASUAL', 43.64, 92, 4.3, 10, 1, 422, 0.83);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Vegan Leather Crossbody 5', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual5.jpg', 'women_CASUAL', 60.16, 26, 4.6, 15, 1, 306, 0.33);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual A-Line Denim Skirt 6', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual6.jpg', 'women_CASUAL', 30.96, 118, 4.5, 20, 0, 73, 0.27);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Oversized Cable Sweater 7', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual7.jpg', 'women_CASUAL', 95.05, 72, 4.2, 0, 0, 269, 0.52);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Lightweight Canvas Shoes 8', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual8.jpg', 'women_CASUAL', 83.21, 129, 3.5, 0, 0, 116, 0.27);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Breathable Linen Pants 9', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual9.jpg', 'women_CASUAL', 33.66, 135, 4.2, 10, 0, 17, 0.08);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Micro-Ribbed Basic Tee 10', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual10.jpg', 'women_CASUAL', 39.13, 124, 4.3, 20, 0, 4, 0.63);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Floral Garden Sundress 11', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual11.jpg', 'women_CASUAL', 26.73, 60, 4.1, 0, 0, 327, 0.48);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual High-Rise Yoga Leggings 12', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual12.jpg', 'women_CASUAL', 59.20, 20, 4.1, 20, 0, 42, 0.87);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Soft Knit Cardigan 13', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual13.jpg', 'women_CASUAL', 90.40, 24, 3.5, 15, 0, 406, 0.37);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Comfort Leather Loafers 14', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual14.jpg', 'women_CASUAL', 87.40, 10, 4.0, 15, 0, 317, 0.91);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Vegan Leather Crossbody 15', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual15.jpg', 'women_CASUAL', 23.45, 114, 4.4, 15, 0, 401, 0.11);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual A-Line Denim Skirt 16', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual16.jpg', 'women_CASUAL', 96.15, 44, 4.2, 5, 0, 387, 0.49);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Oversized Cable Sweater 17', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual17.jpg', 'women_CASUAL', 82.05, 56, 3.7, 0, 0, 130, 0.50);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Lightweight Canvas Shoes 18', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual18.jpg', 'women_CASUAL', 71.88, 124, 4.0, 0, 0, 81, 0.54);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Breathable Linen Pants 19', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual19.jpg', 'women_CASUAL', 78.60, 25, 3.7, 15, 0, 153, 0.34);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Women Casual Micro-Ribbed Basic Tee 20', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'women_casual20.jpg', 'women_CASUAL', 70.48, 30, 4.2, 5, 0, 139, 0.29);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Playful Graphic Tee 1', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual1.jpg', 'kids_CASUAL', 69.49, 34, 5.0, 10, 0, 88, 0.43);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Comfy Cotton Sweatpants 2', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual2.jpg', 'kids_CASUAL', 43.41, 23, 4.4, 15, 0, 238, 0.01);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Active Running Sneakers 3', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual3.jpg', 'kids_CASUAL', 30.66, 74, 3.7, 15, 0, 442, 0.40);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Soft Pajama Set 4', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual4.jpg', 'kids_CASUAL', 29.80, 90, 3.7, 15, 0, 195, 0.94);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Water-Resistant Windbreaker 5', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual5.jpg', 'kids_CASUAL', 61.24, 12, 4.9, 20, 0, 247, 0.34);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Classic Denim Overalls 6', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual6.jpg', 'kids_CASUAL', 67.17, 6, 4.2, 15, 0, 277, 0.10);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Bright Rubber Rain Boots 7', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual7.jpg', 'kids_CASUAL', 96.94, 11, 4.0, 15, 0, 479, 0.50);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Cozy Knit Beanie 8', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual8.jpg', 'kids_CASUAL', 82.48, 93, 4.2, 0, 0, 466, 0.87);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Elastic Waist Shorts 9', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual9.jpg', 'kids_CASUAL', 58.87, 149, 3.5, 5, 1, 423, 0.55);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Full-Zip Fleece Jacket 10', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual10.jpg', 'kids_CASUAL', 78.48, 25, 4.8, 5, 0, 387, 0.02);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Playful Graphic Tee 11', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual11.jpg', 'kids_CASUAL', 67.55, 118, 3.9, 0, 1, 484, 0.33);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Comfy Cotton Sweatpants 12', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual12.jpg', 'kids_CASUAL', 75.91, 98, 3.6, 0, 0, 190, 0.86);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Active Running Sneakers 13', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual13.jpg', 'kids_CASUAL', 23.71, 66, 4.5, 10, 0, 388, 0.75);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Soft Pajama Set 14', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual14.jpg', 'kids_CASUAL', 31.06, 102, 4.1, 20, 0, 148, 0.43);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Water-Resistant Windbreaker 15', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual15.jpg', 'kids_CASUAL', 95.28, 49, 4.6, 10, 1, 409, 0.73);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Classic Denim Overalls 16', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual16.jpg', 'kids_CASUAL', 60.74, 16, 4.3, 10, 0, 336, 0.17);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Bright Rubber Rain Boots 17', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual17.jpg', 'kids_CASUAL', 26.41, 125, 3.5, 10, 0, 116, 0.29);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Cozy Knit Beanie 18', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual18.jpg', 'kids_CASUAL', 53.61, 107, 4.0, 0, 0, 25, 0.57);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Elastic Waist Shorts 19', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual19.jpg', 'kids_CASUAL', 30.72, 60, 4.0, 20, 0, 181, 0.98);
INSERT INTO products (name, description, image, category, price, stock, rating, discount, is_featured, sales_count, ai_score) VALUES ('Kids Casual Full-Zip Fleece Jacket 20', 'Versatile, high-quality piece designed for ultimate comfort and daily style.', 'kids_casual20.jpg', 'kids_CASUAL', 78.15, 122, 4.8, 0, 1, 256, 0.85);
